### ISSUE TITLE
No module named 'layout_configs'

### ISSUE THREAD

**Issue by coolintake** [brad-darksbian/commodities-dashboard#2]
hi, im getting this error: 

  File ~/.spyder-py3/temp.py:19
    import layout_configs as lc
ModuleNotFoundError: No module named 'layout_configs'

PS: new to python and not sure what i'm missing

tks

**Comment by brad-darksbian** [comment]
Layout_config.py is a file in the main code base.  It is largely used to set various display preferences and look and feel attributes of the charting functions.  Either A) make sure that file is in the directory of your code base you are trying to use (since it appears you are doing something beyond just using the code as-is) or B) just go through the functions you are using and remove references to the layout config module.  It won't have a major effect if it's removed.  The entire file just made for a convenient place to put various things that were set for reuse.

If you still have issues, feel free to post up or if it's something you can't get through on your own, feel free to shoot me an email with your code at brad _at_ darksbian.com and I'll do what I can to get you over the hurdle.

**Comment by coolintake** [comment]
Thanks for the response Bradley!

been tinkering with this for sometime, still stuck..however at a different
spot now

here's what I did thus far & what error I'm getting (hopefully its a quick
fix)

1- using macbook, Spydr IDE
2- didn't change anything in Main, Layout, or Business. Only change(s) in
Support Function (attached)

all help is well appreciated




[image: image.png]

[image: image.png]
